### ISSUE TITLE
Refactor FastAPI backend with router

### ISSUE THREAD

**Issue by malhotra5** [NaturalAgents/NaturalAgents#9]
# Current

The backend entrypoint in `/backend/service/listener.py` is one large file

# Requirement

Modularize the different API paths with a FastAPI router. A possible way to modularize for now

1. File/Folder creation, deletion, and renaming in one place
2. All other API paths in another place

**Comment by MichalTirpak** [comment]
Hello, I would like to ask if I could work on this issue.

**Comment by SalimNhiri** [comment]
Hi @malhotra5 , i happy to contribute, can you please assign me for #9

**Comment by malhotra5** [comment]
Hi @SalimNhiri, that you for contributing! I've assign this issue to you. Here is a [guide](https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project) for making contributions in case it helps.
